# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-20 11:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='actors',
            field=models.ManyToManyField(blank=True, to='movie_tracker.Actor'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='keywords',
            field=models.ManyToManyField(blank=True, to='movie_tracker.Keyword'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='release_date',
            field=models.DateField(null=True),
        ),
    ]
