# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-13 10:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movie_tracker', '0005_auto_20180113_0742'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMovie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.TextField(choices=[('watched', 'Watched'), ('not_watched', 'Not Watched')], default='not_watched', max_length=2)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie_tracker.Movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='watched',
            name='movie',
        ),
        migrations.RemoveField(
            model_name='watched',
            name='user',
        ),
        migrations.DeleteModel(
            name='Watched',
        ),
    ]
