# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-13 12:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_tracker', '0007_actormovie'),
        ('movie_tracker', '0006_auto_20180113_1253'),
    ]

    operations = [
    ]
